//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiota.Store.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tokiota.Store.Resources.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountNumber.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional last name.
        /// </summary>
        public static string AdditionalLastName {
            get {
                return ResourceManager.GetString("AdditionalLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressDoor.
        /// </summary>
        public static string AddressDoor {
            get {
                return ResourceManager.GetString("AddressDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressFloor.
        /// </summary>
        public static string AddressFloor {
            get {
                return ResourceManager.GetString("AddressFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressNumber.
        /// </summary>
        public static string AddressNumber {
            get {
                return ResourceManager.GetString("AddressNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AditionalAddress.
        /// </summary>
        public static string AditionalAddress {
            get {
                return ResourceManager.GetString("AditionalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BankCode.
        /// </summary>
        public static string BankCode {
            get {
                return ResourceManager.GetString("BankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BranchCode.
        /// </summary>
        public static string BranchCode {
            get {
                return ResourceManager.GetString("BranchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CabinCrewCertificateDate.
        /// </summary>
        public static string CabinCrewCertificateDate {
            get {
                return ResourceManager.GetString("CabinCrewCertificateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckDigits.
        /// </summary>
        public static string CheckDigits {
            get {
                return ResourceManager.GetString("CheckDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChildBirthYear1.
        /// </summary>
        public static string ChildBirthYear1 {
            get {
                return ResourceManager.GetString("ChildBirthYear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChildBirthYear2.
        /// </summary>
        public static string ChildBirthYear2 {
            get {
                return ResourceManager.GetString("ChildBirthYear2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChildBirthYear3.
        /// </summary>
        public static string ChildBirthYear3 {
            get {
                return ResourceManager.GetString("ChildBirthYear3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChildBirthYear4.
        /// </summary>
        public static string ChildBirthYear4 {
            get {
                return ResourceManager.GetString("ChildBirthYear4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ConfirmPasswordErrorMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationalLevel.
        /// </summary>
        public static string EducationalLevel {
            get {
                return ResourceManager.GetString("EducationalLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FamilyPhone.
        /// </summary>
        public static string FamilyPhone {
            get {
                return ResourceManager.GetString("FamilyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FamilySituation.
        /// </summary>
        public static string FamilySituation {
            get {
                return ResourceManager.GetString("FamilySituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user email..
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaritalStatus.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nif.
        /// </summary>
        public static string Nif {
            get {
                return ResourceManager.GetString("Nif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NifExpirationDate.
        /// </summary>
        public static string NifExpirationDate {
            get {
                return ResourceManager.GetString("NifExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostalCode.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreviousExperienceFromDate.
        /// </summary>
        public static string PreviousExperienceFromDate {
            get {
                return ResourceManager.GetString("PreviousExperienceFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreviousExperienceToDate.
        /// </summary>
        public static string PreviousExperienceToDate {
            get {
                return ResourceManager.GetString("PreviousExperienceToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResidingAbroad.
        /// </summary>
        public static string ResidingAbroad {
            get {
                return ResourceManager.GetString("ResidingAbroad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SocialIsuranceNumber.
        /// </summary>
        public static string SocialIsuranceNumber {
            get {
                return ResourceManager.GetString("SocialIsuranceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpouseNif.
        /// </summary>
        public static string SpouseNif {
            get {
                return ResourceManager.GetString("SpouseNif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetType.
        /// </summary>
        public static string StreetType {
            get {
                return ResourceManager.GetString("StreetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string StringLengthErrorMessage {
            get {
                return ResourceManager.GetString("StringLengthErrorMessage", resourceCulture);
            }
        }
    }
}
